# Generated by Django 6.0.3 on 2026-03-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_producto_disponible_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuacceso',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='tienda.menuacceso'),
        ),
    ]
