# Generated by Django 6.0.3 on 2026-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_carritodb_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_critico',
            field=models.IntegerField(default=5),
        ),
    ]
